version: '3.8'

services:
  app1:
    build: 
      context: .
      dockerfile: Dockerfile
    image: server-lord-week1-img1
    ports:
      - "8081:8080"
    volumes:
      - .:/app
  app2:
    build: 
      context: .
      dockerfile: Dockerfile
    image: server-lord-week1-img2
    ports:
      - "8082:8080"
    volumes:
      - .:/app
  app3:
    build: 
      context: .
      dockerfile: Dockerfile
    image: server-lord-week1-img3
    ports:
      - "8083:8080"
    volumes:
      - .:/app
  nginx:
    image: nginx:1.27
    ports: 
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf